image: Visual Studio 2019
configuration: z_CI_config
environment:
  codegov_token:
    secure: HdCtITC0uUqTr/C3OSs4M1Ao79R8UULQtiRUqSrGuQpmqrZXPfNGz+s0uibvyz49
build_script:
- ps: Invoke-Expression .\CI_script.ps1 
artifacts:
- path: 'Artifacts\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: csIJIcTOAQ930rX3eOmufGO46xPDHZxrRpjCyU5xEQz3EwWx7+1Ed4pUE0prQyqY
  on:
    branch: /^(develop)$/