steps:
- task: UseDotNet@2
  inputs:
    version: '3.0.100-preview3-010431'
- task: PowerShell@2
  displayName: 'Nuke build'
  inputs:
    targetType: filePath
    filePath: ./build.ps1
    arguments: 'Pack Coverage Push -ApiKey $env:NugetToken'
  env:
    NugetToken: $(nuget_token)
- task: PublishTestResults@2
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '*.trx'
    searchFolder: '$(Build.SourcesDirectory)/TestResults'
- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/coverage/Cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)/coverage'