steps:
- task: UseDotNet@2
  inputs:
    version: '3.0.100-preview3-010431'
- task: PowerShell@2
  displayName: 'Nuke build'
  inputs:
    targetType: filePath
    filePath: ./build.ps1
    arguments: 'Pack Push -ApiKey foo'