steps:
- task: UseDotNet@2
  inputs:
    version: '3.0.0'
- task: PowerShell@2
  displayName: 'PowerShell Script'
  inputs:
    targetType: filePath
    filePath: ./build.ps1
    arguments: 'Pack Push -ApiKey foo'